### ISSUE TITLE
Duat.itermcolors not working

### ISSUE THREAD

**Issue by RowanKaag** [inket/Duat.terminal#3]
Did a clean install of OS X 👉 installed iTerm2 👉 git clone'd the repo 👉 tried manual import & double clicking the .itermcolors file

can't manage to get the colors to work.

**Comment by inket** [comment]
You're using stable iTerm 2 ?

It seems it only works with iTerm 2.9 beta, so try that. The settings will persist so after you install it on the beta and select it, it'll be applied in the stable version too.

**Comment by RowanKaag** [comment]
That did the trick. Thank you.
